//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.EmbratelIntranet.Home
{
    using Microsoft.SharePoint;
    using System;


    public partial class IntranetData : Microsoft.SharePoint.Linq.DataContext
    {

        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion

        public IntranetData(string requestUrl) :
            base(requestUrl)
        {
            this.OnCreated();
        }

        /// <summary>
        /// Armazena os links do menu superior
        /// </summary>
        [Microsoft.SharePoint.Linq.ListAttribute(Name = "Acesso Rápido")]
        public Microsoft.SharePoint.Linq.EntityList<AcessoRápido> AcessoRápido
        {
            get
            {
                return this.GetList<AcessoRápido>("Acesso Rápido");
            }
        }

        /// <summary>
        /// My List Instance
        /// </summary>
        [Microsoft.SharePoint.Linq.ListAttribute(Name = "Alertas")]
        public Microsoft.SharePoint.Linq.EntityList<Alerta> Alertas
        {
            get
            {
                return this.GetList<Alerta>("Alertas");
            }
        }

        /// <summary>
        /// My List Instance
        /// </summary>
        [Microsoft.SharePoint.Linq.ListAttribute(Name = "Aniversariantes")]
        public Microsoft.SharePoint.Linq.EntityList<Aniversariante> Aniversariantes
        {
            get
            {
                return this.GetList<Aniversariante>("Aniversariantes");
            }
        }

        /// <summary>
        /// My List Instance
        /// </summary>
        [Microsoft.SharePoint.Linq.ListAttribute(Name = "Instrumentos Normativos")]
        public Microsoft.SharePoint.Linq.EntityList<Document> InstrumentosNormativos
        {
            get
            {
                return this.GetList<Document>("Instrumentos Normativos");
            }
        }

        /// <summary>
        /// My List Instance
        /// </summary>
        [Microsoft.SharePoint.Linq.ListAttribute(Name = "Notícias")]
        public Microsoft.SharePoint.Linq.EntityList<Notícia> Notícias
        {
            get
            {
                return this.GetList<Notícia>("Notícias");
            }
        }


        /// <summary>
        /// My List Instance
        /// </summary>
        [Microsoft.SharePoint.Linq.ListAttribute(Name = "SaiuNoMural")]
        public Microsoft.SharePoint.Linq.EntityList<Notícia> SaiuNoMural
        {
            get
            {
                return this.GetList<Notícia>("SaiuNoMural");
            }
        }





        /// <summary>
        /// My List Instance
        /// </summary>
        [Microsoft.SharePoint.Linq.ListAttribute(Name = "Popup")]
        public Microsoft.SharePoint.Linq.EntityList<Popup> Popup
        {
            get
            {
                return this.GetList<Popup>("Popup");
            }
        }

        /// <summary>
        /// Lista de Sistemas de A a Z
        /// </summary>
        [Microsoft.SharePoint.Linq.ListAttribute(Name = "Sistemas de A a Z")]
        public Microsoft.SharePoint.Linq.EntityList<Sistema> SistemasDeAAZ
        {
            get
            {
                return this.GetList<Sistema>("Sistemas de A a Z");
            }
        }

        /// <summary>
        /// My List Instance
        /// </summary>
        [Microsoft.SharePoint.Linq.ListAttribute(Name = "Temas Intranet")]
        public Microsoft.SharePoint.Linq.EntityList<TemaIntranet> TemasIntranet
        {
            get
            {
                return this.GetList<TemaIntranet>("Temas Intranet");
            }
        }

        /// <summary>
        /// My List Instance
        /// </summary>
        [Microsoft.SharePoint.Linq.ListAttribute(Name = "Conteúdo de Mídia")]
        public Microsoft.SharePoint.Linq.EntityList<ConteudoMidia> ConteudoMidia
        {
            get
            {
                return this.GetList<ConteudoMidia>("Conteúdo de Mídia");
            }
        }

        /// <summary>
        /// My List Instance
        /// </summary>
        [Microsoft.SharePoint.Linq.ListAttribute(Name = "Web TV")]
        public Microsoft.SharePoint.Linq.EntityList<WebTV> WebTV
        {
            get
            {
                return this.GetList<WebTV>("Web TV");
            }
        }
    }

    /// <summary>
    /// Create a new list item.
    /// </summary>
    [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "Item", Id = "0x01")]
    [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(Document))]
    [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(Alerta))]
    [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(Aniversariante))]
    [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(Notícia))]
    [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(Link))]
    [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(TemaIntranet))]
    [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(ConteudoMidia))]
    [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(WebTV))]
    public partial class Item : Microsoft.SharePoint.Linq.ITrackEntityState, Microsoft.SharePoint.Linq.ITrackOriginalValues, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging
    {

        private System.Nullable<int> _id;

        private System.Nullable<int> _version;

        private string _path;

        private Microsoft.SharePoint.Linq.EntityState _entityState;

        private System.Collections.Generic.IDictionary<string, object> _originalValues;

        private string _title;

        private System.Nullable<System.DateTime> _criado;


        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate();
        partial void OnCreated();
        #endregion


        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Criado", Storage = "_criado", Required = true, FieldType = "DateTime")]
        public System.Nullable<System.DateTime> Criado
        {
            get
            {
                return this._criado;
            }
            set
            {
                if ((value != this._criado))
                {
                    this.OnPropertyChanging("Criado", this._criado);
                    this._criado = value;
                    this.OnPropertyChanged("Criado");
                }
            }
        }


        Microsoft.SharePoint.Linq.EntityState Microsoft.SharePoint.Linq.ITrackEntityState.EntityState
        {
            get
            {
                return this._entityState;
            }
            set
            {
                if ((value != this._entityState))
                {
                    this._entityState = value;
                }
            }
        }

        System.Collections.Generic.IDictionary<string, object> Microsoft.SharePoint.Linq.ITrackOriginalValues.OriginalValues
        {
            get
            {
                if ((null == this._originalValues))
                {
                    this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
                }
                return this._originalValues;
            }
        }

        public Item()
        {
            this.OnCreated();
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "ID", Storage = "_id", ReadOnly = true, FieldType = "Counter")]
        public System.Nullable<int> Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((value != this._id))
                {
                    this.OnPropertyChanging("Id", this._id);
                    this._id = value;
                    this.OnPropertyChanged("Id");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "owshiddenversion", Storage = "_version", ReadOnly = true, FieldType = "Integer")]
        public System.Nullable<int> Version
        {
            get
            {
                return this._version;
            }
            set
            {
                if ((value != this._version))
                {
                    this.OnPropertyChanging("Version", this._version);
                    this._version = value;
                    this.OnPropertyChanged("Version");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "FileDirRef", Storage = "_path", ReadOnly = true, FieldType = "Lookup", IsLookupValue = true)]
        public string Path
        {
            get
            {
                return this._path;
            }
            set
            {
                if ((value != this._path))
                {
                    this.OnPropertyChanging("Path", this._path);
                    this._path = value;
                    this.OnPropertyChanged("Path");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Title", Storage = "_title", Required = true, FieldType = "Text")]
        public virtual string Title
        {
            get
            {
                return this._title;
            }
            set
            {
                if ((value != this._title))
                {
                    this.OnPropertyChanging("Title", this._title);
                    this._title = value;
                    this.OnPropertyChanged("Title");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if ((null != this.PropertyChanged))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        protected virtual void OnPropertyChanging(string propertyName, object value)
        {
            if ((null == this._originalValues))
            {
                this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
            }
            if ((false == this._originalValues.ContainsKey(propertyName)))
            {
                this._originalValues.Add(propertyName, value);
            }
            if ((null != this.PropertyChanging))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }
    }

    /// <summary>
    /// Create a new document.
    /// </summary>
    [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "Document", Id = "0x0101")]
    [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(AcessoRápido))]
    [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(Popup))]
    public partial class Document : Item
    {

        private string _name;

        private string _documentModifiedBy;

        private string _documentCreatedBy;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate();
        partial void OnCreated();
        #endregion

        public Document()
        {
            this.OnCreated();
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "FileLeafRef", Storage = "_name", Required = true, FieldType = "File")]
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((value != this._name))
                {
                    this.OnPropertyChanging("Name", this._name);
                    this._name = value;
                    this.OnPropertyChanged("Name");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Modified_x0020_By", Storage = "_documentModifiedBy", ReadOnly = true, FieldType = "Text")]
        public virtual string DocumentModifiedBy
        {
            get
            {
                return this._documentModifiedBy;
            }
            set
            {
                if ((value != this._documentModifiedBy))
                {
                    this.OnPropertyChanging("DocumentModifiedBy", this._documentModifiedBy);
                    this._documentModifiedBy = value;
                    this.OnPropertyChanged("DocumentModifiedBy");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Created_x0020_By", Storage = "_documentCreatedBy", ReadOnly = true, FieldType = "Text")]
        public virtual string DocumentCreatedBy
        {
            get
            {
                return this._documentCreatedBy;
            }
            set
            {
                if ((value != this._documentCreatedBy))
                {
                    this.OnPropertyChanging("DocumentCreatedBy", this._documentCreatedBy);
                    this._documentCreatedBy = value;
                    this.OnPropertyChanged("DocumentCreatedBy");
                }
            }
        }
    }

    /// <summary>
    /// Create a new link to a Web page or other resource.
    /// </summary>
    [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "Link", Id = "0x0105")]
    [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(Sistema))]
    public partial class Link : Item
    {

        private string _uRL;

        private string _comments;

        private string _uRL0;

        private string _uRL1;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate();
        partial void OnCreated();
        #endregion

        public Link()
        {
            this.OnCreated();
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "URL", Storage = "_uRL", Required = true, FieldType = "Url")]
        public string URL
        {
            get
            {
                return this._uRL;
            }
            set
            {
                if ((value != this._uRL))
                {
                    this.OnPropertyChanging("URL", this._uRL);
                    this._uRL = value;
                    this.OnPropertyChanged("URL");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Comments", Storage = "_comments", FieldType = "Note")]
        public string Comments
        {
            get
            {
                return this._comments;
            }
            set
            {
                if ((value != this._comments))
                {
                    this.OnPropertyChanging("Comments", this._comments);
                    this._comments = value;
                    this.OnPropertyChanged("Comments");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "URLwMenu", Storage = "_uRL0", ReadOnly = true, FieldType = "Computed")]
        public string URL0
        {
            get
            {
                return this._uRL0;
            }
            set
            {
                if ((value != this._uRL0))
                {
                    this.OnPropertyChanging("URL0", this._uRL0);
                    this._uRL0 = value;
                    this.OnPropertyChanged("URL0");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "URLNoMenu", Storage = "_uRL1", ReadOnly = true, FieldType = "Computed")]
        public string URL1
        {
            get
            {
                return this._uRL1;
            }
            set
            {
                if ((value != this._uRL1))
                {
                    this.OnPropertyChanging("URL1", this._uRL1);
                    this._uRL1 = value;
                    this.OnPropertyChanged("URL1");
                }
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
        public override string Title
        {
            get
            {
                throw new System.InvalidOperationException("Field Title was removed from content type Link.");
            }
            set
            {
                throw new System.InvalidOperationException("Field Title was removed from content type Link.");
            }
        }
    }

    /// <summary>
    /// Create a new link to a Web page or other resource.
    /// </summary>
    [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "Link", Id = "0x0105", List = "Sistemas de A a Z")]
    public partial class Sistema : Link
    {

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate();
        partial void OnCreated();
        #endregion

        public Sistema()
        {
            this.OnCreated();
        }
    }

    [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "ListFieldsContentType", Id = "0x01", List = "Alertas")]
    public partial class Alerta : Item
    {

        private string _texto;

        private System.Nullable<Categoria> _Categoria;

        //private System.Nullable<int> _ModerationStatus;

        private string _uRL;

        private System.Nullable<System.DateTime> _dataInicio;

        private System.Nullable<System.DateTime> _dataFim;

        private System.Nullable<Destino> _destino;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate();
        partial void OnCreated();
        #endregion

        public Alerta()
        {
            this.OnCreated();
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Texto", Storage = "_texto", Required = true, FieldType = "Note")]
        public string Texto
        {
            get
            {
                return this._texto;
            }
            set
            {
                if ((value != this._texto))
                {
                    this.OnPropertyChanging("Texto", this._texto);
                    this._texto = value;
                    this.OnPropertyChanged("Texto");
                }
            }
        }

        //[Microsoft.SharePoint.Linq.ColumnAttribute(Name = "_ModerationStatus", Storage = "_ModerationStatus", FieldType = "Number")]
        //public System.Nullable<int> ModerationStatus
        //{
        //    get
        //    {
        //        return this._ModerationStatus;
        //    }
        //    set
        //    {
        //        if ((value != this._ModerationStatus))
        //        {
        //            this.OnPropertyChanging("ModerationStatus", this._ModerationStatus);
        //            this._ModerationStatus = value;
        //            this.OnPropertyChanged("ModerationStatus");
        //        }
        //    }
        //}

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Categoria", Storage = "_Categoria", FieldType = "Choice")]
        public System.Nullable<Categoria> Categoria
        {
            get
            {
                return this._Categoria;
            }
            set
            {
                if ((value != this._Categoria))
                {
                    this.OnPropertyChanging("Categoria", this._Categoria);
                    this._Categoria = value;
                    this.OnPropertyChanged("Categoria");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "URL", Storage = "_uRL", FieldType = "Url")]
        public string URL
        {
            get
            {
                return this._uRL;
            }
            set
            {
                if ((value != this._uRL))
                {
                    this.OnPropertyChanging("URL", this._uRL);
                    this._uRL = value;
                    this.OnPropertyChanged("URL");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DataInicio", Storage = "_dataInicio", Required = true, FieldType = "DateTime")]
        public System.Nullable<System.DateTime> DataInicio
        {
            get
            {
                return this._dataInicio;
            }
            set
            {
                if ((value != this._dataInicio))
                {
                    this.OnPropertyChanging("DataInicio", this._dataInicio);
                    this._dataInicio = value;
                    this.OnPropertyChanged("DataInicio");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DataFim", Storage = "_dataFim", Required = true, FieldType = "DateTime")]
        public System.Nullable<System.DateTime> DataFim
        {
            get
            {
                return this._dataFim;
            }
            set
            {
                if ((value != this._dataFim))
                {
                    this.OnPropertyChanging("DataFim", this._dataFim);
                    this._dataFim = value;
                    this.OnPropertyChanged("DataFim");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Destino", Storage = "_destino", FieldType = "Choice")]
        public System.Nullable<Destino> Destino
        {
            get
            {
                return this._destino;
            }
            set
            {
                if ((value != this._destino))
                {
                    this.OnPropertyChanging("Destino", this._destino);
                    this._destino = value;
                    this.OnPropertyChanged("Destino");
                }
            }
        }
    }

    [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "ListFieldsContentType", Id = "0x01", List = "Aniversariantes")]
    public partial class Aniversariante : Item
    {

        private string _fotoUrl;

        private string _sobrenome;

        private string _departamento;

        private System.Nullable<double> _diaAniversario;

        private System.Nullable<double> _mesAniversario;

        private System.Nullable<DateTime> _dataRef;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate();
        partial void OnCreated();
        #endregion

        public Aniversariante()
        {
            this.OnCreated();
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DataRef", Storage = "_dataRef", FieldType = "DateTime")]
        public System.Nullable<DateTime> DataRef
        {
            get
            {
                return this._dataRef;
            }
            set
            {
                if ((value != this._dataRef))
                {
                    this.OnPropertyChanging("DataRef", this._dataRef);
                    this._dataRef = value;
                    this.OnPropertyChanged("DataRef");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "FotoUrl", Storage = "_fotoUrl", FieldType = "Url")]
        public string FotoUrl
        {
            get
            {
                return this._fotoUrl;
            }
            set
            {
                if ((value != this._fotoUrl))
                {
                    this.OnPropertyChanging("FotoUrl", this._fotoUrl);
                    this._fotoUrl = value;
                    this.OnPropertyChanged("FotoUrl");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Sobrenome", Storage = "_sobrenome", FieldType = "Text")]
        public string Sobrenome
        {
            get
            {
                return this._sobrenome;
            }
            set
            {
                if ((value != this._sobrenome))
                {
                    this.OnPropertyChanging("Sobrenome", this._sobrenome);
                    this._sobrenome = value;
                    this.OnPropertyChanged("Sobrenome");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Departamento", Storage = "_departamento", FieldType = "Text")]
        public string Departamento
        {
            get
            {
                return this._departamento;
            }
            set
            {
                if ((value != this._departamento))
                {
                    this.OnPropertyChanging("Departamento", this._departamento);
                    this._departamento = value;
                    this.OnPropertyChanged("Departamento");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DiaAniversario", Storage = "_diaAniversario", FieldType = "Number")]
        public System.Nullable<double> DiaAniversario
        {
            get
            {
                return this._diaAniversario;
            }
            set
            {
                if ((value != this._diaAniversario))
                {
                    this.OnPropertyChanging("DiaAniversario", this._diaAniversario);
                    this._diaAniversario = value;
                    this.OnPropertyChanged("DiaAniversario");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "MesAniversario", Storage = "_mesAniversario", FieldType = "Number")]
        public System.Nullable<double> MesAniversario
        {
            get
            {
                return this._mesAniversario;
            }
            set
            {
                if ((value != this._mesAniversario))
                {
                    this.OnPropertyChanging("MesAniversario", this._mesAniversario);
                    this._mesAniversario = value;
                    this.OnPropertyChanged("MesAniversario");
                }
            }
        }
    }

    [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "ListFieldsContentType", Id = "0x01", List = "Notícias")]
    public partial class Notícia : Item
    {

        private string _chamada;

        private string _texto;

        private System.Nullable<System.DateTime> _dataInicio;

        private System.Nullable<System.DateTime> _dataFim;

        private string _aprovado;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate();
        partial void OnCreated();
        #endregion

        public Notícia()
        {
            this.OnCreated();
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Chamada", Storage = "_chamada", Required = true, FieldType = "Text")]
        public string Chamada
        {
            get
            {
                return this._chamada;
            }
            set
            {
                if ((value != this._chamada))
                {
                    this.OnPropertyChanging("Chamada", this._chamada);
                    this._chamada = value;
                    this.OnPropertyChanged("Chamada");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Texo", Storage = "_texto", Required = true, FieldType = "Note")]
        public string Texto
        {
            get
            {
                return this._texto;
            }
            set
            {
                if ((value != this._texto))
                {
                    this.OnPropertyChanging("Texto", this._texto);
                    this._texto = value;
                    this.OnPropertyChanged("Texto");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "_ModerationStatus", Storage = "_aprovado", Required = true, FieldType = "Text")]
        public string Aprovado
        {
            get
            {
                return this._aprovado;
            }
            set
            {
                if ((value != this._aprovado))
                {
                    this.OnPropertyChanging("Aprovado", this._aprovado);
                    this._aprovado = value;
                    this.OnPropertyChanged("Aprovado");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DataInicio", Storage = "_dataInicio", Required = true, FieldType = "DateTime")]
        public System.Nullable<System.DateTime> DataInicio
        {
            get
            {
                return this._dataInicio;
            }
            set
            {
                if ((value != this._dataInicio))
                {
                    this.OnPropertyChanging("DataInicio", this._dataInicio);
                    this._dataInicio = value;
                    this.OnPropertyChanged("DataInicio");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DataFim", Storage = "_dataFim", Required = true, FieldType = "DateTime")]
        public System.Nullable<System.DateTime> DataFim
        {
            get
            {
                return this._dataFim;
            }
            set
            {
                if ((value != this._dataFim))
                {
                    this.OnPropertyChanging("DataFim", this._dataFim);
                    this._dataFim = value;
                    this.OnPropertyChanged("DataFim");
                }
            }
        }
    }

    [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "ListFieldsContentType", Id = "0x01", List = "Temas Intranet")]
    public partial class TemaIntranet : Item
    {

        private System.Nullable<System.DateTime> _dataInicio;

        private System.Nullable<System.DateTime> _dataFim;

        private System.Nullable<bool> _definirLayoutPadrao;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate();
        partial void OnCreated();
        #endregion

        public TemaIntranet()
        {
            this.OnCreated();
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DataInicio", Storage = "_dataInicio", FieldType = "DateTime")]
        public System.Nullable<System.DateTime> DataInicio
        {
            get
            {
                return this._dataInicio;
            }
            set
            {
                if ((value != this._dataInicio))
                {
                    this.OnPropertyChanging("DataInicio", this._dataInicio);
                    this._dataInicio = value;
                    this.OnPropertyChanged("DataInicio");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DataFim", Storage = "_dataFim", FieldType = "DateTime")]
        public System.Nullable<System.DateTime> DataFim
        {
            get
            {
                return this._dataFim;
            }
            set
            {
                if ((value != this._dataFim))
                {
                    this.OnPropertyChanging("DataFim", this._dataFim);
                    this._dataFim = value;
                    this.OnPropertyChanged("DataFim");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DefinirLayoutPadrao", Storage = "_definirLayoutPadrao", FieldType = "Boolean")]
        public System.Nullable<bool> DefinirLayoutPadrao
        {
            get
            {
                return this._definirLayoutPadrao;
            }
            set
            {
                if ((value != this._definirLayoutPadrao))
                {
                    this.OnPropertyChanging("DefinirLayoutPadrao", this._definirLayoutPadrao);
                    this._definirLayoutPadrao = value;
                    this.OnPropertyChanged("DefinirLayoutPadrao");
                }
            }
        }
    }
     
    [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "ListFieldsContentType", Id = "0x01", List = "Conteúdo de Mídia")]
    public partial class ConteudoMidia : Item
    {

        private System.Nullable<System.DateTime> _dataInicio;

        private System.Nullable<System.DateTime> _dataFim;

        private System.Nullable<double> _posicao;

        private System.Nullable<double> _duracao;

        private string _uRL;

        private System.Nullable<Destino> _destino;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate();
        partial void OnCreated();
        #endregion

        public ConteudoMidia()
        {
            this.OnCreated();
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DataInicio", Storage = "_dataInicio", Required = true, FieldType = "DateTime")]
        public System.Nullable<System.DateTime> DataInicio
        {
            get
            {
                return this._dataInicio;
            }
            set
            {
                if ((value != this._dataInicio))
                {
                    this.OnPropertyChanging("DataInicio", this._dataInicio);
                    this._dataInicio = value;
                    this.OnPropertyChanged("DataInicio");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DataFim", Storage = "_dataFim", Required = true, FieldType = "DateTime")]
        public System.Nullable<System.DateTime> DataFim
        {
            get
            {
                return this._dataFim;
            }
            set
            {
                if ((value != this._dataFim))
                {
                    this.OnPropertyChanging("DataFim", this._dataFim);
                    this._dataFim = value;
                    this.OnPropertyChanged("DataFim");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Posicao", Storage = "_posicao", FieldType = "Number")]
        public System.Nullable<double> Posicao
        {
            get
            {
                return this._posicao;
            }
            set
            {
                if ((value != this._posicao))
                {
                    this.OnPropertyChanging("Posicao", this._posicao);
                    this._posicao = value;
                    this.OnPropertyChanged("Posicao");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Duracao", Storage = "_duracao", Required = true, FieldType = "Number")]
        public System.Nullable<double> Duracao
        {
            get
            {
                return this._duracao;
            }
            set
            {
                if ((value != this._duracao))
                {
                    this.OnPropertyChanging("Duracao", this._duracao);
                    this._duracao = value;
                    this.OnPropertyChanged("Duracao");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "URL", Storage = "_uRL", FieldType = "Url")]
        public string URL
        {
            get
            {
                return this._uRL;
            }
            set
            {
                if ((value != this._uRL))
                {
                    this.OnPropertyChanging("URL", this._uRL);
                    this._uRL = value;
                    this.OnPropertyChanged("URL");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Destino", Storage = "_destino", FieldType = "Choice")]
        public System.Nullable<Destino> Destino
        {
            get
            {
                return this._destino;
            }
            set
            {
                if ((value != this._destino))
                {
                    this.OnPropertyChanging("Destino", this._destino);
                    this._destino = value;
                    this.OnPropertyChanged("Destino");
                }
            }
        }
    }

    [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "ListFieldsContentType", Id = "0x01", List = "Web TV")]
    public partial class WebTV : Item
    {

        private string _chamada;

        private string _linkPrograma;

        private System.Nullable<System.DateTime> _data;

        private System.Nullable<double> _duracao;

        private string _contato;

        private System.Nullable<Tipo> _tipo;

        private System.Nullable<Status> _status;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate();
        partial void OnCreated();
        #endregion

        public WebTV()
        {
            this.OnCreated();
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Chamada", Storage = "_chamada", FieldType = "Text")]
        public string Chamada
        {
            get
            {
                return this._chamada;
            }
            set
            {
                if ((value != this._chamada))
                {
                    this.OnPropertyChanging("Chamada", this._chamada);
                    this._chamada = value;
                    this.OnPropertyChanged("Chamada");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "LinkPrograma", Storage = "_linkPrograma", FieldType = "Url")]
        public string LinkPrograma
        {
            get
            {
                return this._linkPrograma;
            }
            set
            {
                if ((value != this._linkPrograma))
                {
                    this.OnPropertyChanging("LinkPrograma", this._linkPrograma);
                    this._linkPrograma = value;
                    this.OnPropertyChanged("LinkPrograma");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Data1", Storage = "_data", FieldType = "DateTime")]
        public System.Nullable<System.DateTime> Data
        {
            get
            {
                return this._data;
            }
            set
            {
                if ((value != this._data))
                {
                    this.OnPropertyChanging("Data", this._data);
                    this._data = value;
                    this.OnPropertyChanged("Data");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Duracao", Storage = "_duracao", FieldType = "Number")]
        public System.Nullable<double> Duracao
        {
            get
            {
                return this._duracao;
            }
            set
            {
                if ((value != this._duracao))
                {
                    this.OnPropertyChanging("Duracao", this._duracao);
                    this._duracao = value;
                    this.OnPropertyChanged("Duracao");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Contato", Storage = "_contato", FieldType = "Text")]
        public string Contato
        {
            get
            {
                return this._contato;
            }
            set
            {
                if ((value != this._contato))
                {
                    this.OnPropertyChanging("Contato", this._contato);
                    this._contato = value;
                    this.OnPropertyChanged("Contato");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Tipo", Storage = "_tipo", FieldType = "Choice")]
        public System.Nullable<Tipo> Tipo
        {
            get
            {
                return this._tipo;
            }
            set
            {
                if ((value != this._tipo))
                {
                    this.OnPropertyChanging("Tipo", this._tipo);
                    this._tipo = value;
                    this.OnPropertyChanged("Tipo");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Status", Storage = "_status", FieldType = "Choice")]
        public System.Nullable<Status> Status
        {
            get
            {
                return this._status;
            }
            set
            {
                if ((value != this._status))
                {
                    this.OnPropertyChanging("Status", this._status);
                    this._status = value;
                    this.OnPropertyChanged("Status");
                }
            }
        }
    }

    [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "ListFieldsContentType", Id = "0x0101", List = "Acesso Rápido")]
    public partial class AcessoRápido : Document
    {

        private System.Nullable<double> _posicao;

        private string _uRL;

        private System.Nullable<Destino> _destino;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate();
        partial void OnCreated();
        #endregion

        public AcessoRápido()
        {
            this.OnCreated();
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Posicao", Storage = "_posicao", FieldType = "Number")]
        public System.Nullable<double> Posicao
        {
            get
            {
                return this._posicao;
            }
            set
            {
                if ((value != this._posicao))
                {
                    this.OnPropertyChanging("Posicao", this._posicao);
                    this._posicao = value;
                    this.OnPropertyChanged("Posicao");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "URL", Storage = "_uRL", FieldType = "Url")]
        public string URL
        {
            get
            {
                return this._uRL;
            }
            set
            {
                if ((value != this._uRL))
                {
                    this.OnPropertyChanging("URL", this._uRL);
                    this._uRL = value;
                    this.OnPropertyChanged("URL");
                }
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
        public override string Name
        {
            get
            {
                throw new System.InvalidOperationException("Field FileLeafRef was removed from content type ListFieldsContentType.");
            }
            set
            {
                throw new System.InvalidOperationException("Field FileLeafRef was removed from content type ListFieldsContentType.");
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
        public override string DocumentModifiedBy
        {
            get
            {
                throw new System.InvalidOperationException("Field Modified_x0020_By was removed from content type ListFieldsContentType.");
            }
            set
            {
                throw new System.InvalidOperationException("Field Modified_x0020_By was removed from content type ListFieldsContentType.");
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
        public override string DocumentCreatedBy
        {
            get
            {
                throw new System.InvalidOperationException("Field Created_x0020_By was removed from content type ListFieldsContentType.");
            }
            set
            {
                throw new System.InvalidOperationException("Field Created_x0020_By was removed from content type ListFieldsContentType.");
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Destino", Storage = "_destino", FieldType = "Choice")]
        public System.Nullable<Destino> Destino
        {
            get
            {
                return this._destino;
            }
            set
            {
                if ((value != this._destino))
                {
                    this.OnPropertyChanging("Destino", this._destino);
                    this._destino = value;
                    this.OnPropertyChanged("Destino");
                }
            }
        }
    }

    [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "ListFieldsContentType", Id = "0x0101", List = "Popup")]
    public partial class Popup : Document
    {

        private System.Nullable<System.DateTime> _dataInicio;

        private System.Nullable<System.DateTime> _dataFim;

        private System.Nullable<double> _quantidadeExibicoes;

        private System.Nullable<double> _duracao;

        private System.Nullable<bool> _fundoEscuro;

        private string _uRL;

        private System.Nullable<PeriodoExibicao> _periodoExibicao;

        private System.Nullable<Destino2> _destino;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate();
        partial void OnCreated();
        #endregion

        public Popup()
        {
            this.OnCreated();
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DataInicio", Storage = "_dataInicio", Required = true, FieldType = "DateTime")]
        public System.Nullable<System.DateTime> DataInicio
        {
            get
            {
                return this._dataInicio;
            }
            set
            {
                if ((value != this._dataInicio))
                {
                    this.OnPropertyChanging("DataInicio", this._dataInicio);
                    this._dataInicio = value;
                    this.OnPropertyChanged("DataInicio");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "DataFim", Storage = "_dataFim", Required = true, FieldType = "DateTime")]
        public System.Nullable<System.DateTime> DataFim
        {
            get
            {
                return this._dataFim;
            }
            set
            {
                if ((value != this._dataFim))
                {
                    this.OnPropertyChanging("DataFim", this._dataFim);
                    this._dataFim = value;
                    this.OnPropertyChanged("DataFim");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "QuantidadeExibicoes", Storage = "_quantidadeExibicoes", FieldType = "Number")]
        public System.Nullable<double> QuantidadeExibicoes
        {
            get
            {
                return this._quantidadeExibicoes;
            }
            set
            {
                if ((value != this._quantidadeExibicoes))
                {
                    this.OnPropertyChanging("QuantidadeExibicoes", this._quantidadeExibicoes);
                    this._quantidadeExibicoes = value;
                    this.OnPropertyChanged("QuantidadeExibicoes");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Duracao", Storage = "_duracao", Required = true, FieldType = "Number")]
        public System.Nullable<double> Duracao
        {
            get
            {
                return this._duracao;
            }
            set
            {
                if ((value != this._duracao))
                {
                    this.OnPropertyChanging("Duracao", this._duracao);
                    this._duracao = value;
                    this.OnPropertyChanged("Duracao");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "FundoEscuro", Storage = "_fundoEscuro", FieldType = "Boolean")]
        public System.Nullable<bool> FundoEscuro
        {
            get
            {
                return this._fundoEscuro;
            }
            set
            {
                if ((value != this._fundoEscuro))
                {
                    this.OnPropertyChanging("FundoEscuro", this._fundoEscuro);
                    this._fundoEscuro = value;
                    this.OnPropertyChanged("FundoEscuro");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "URL", Storage = "_uRL", FieldType = "Url")]
        public string URL
        {
            get
            {
                return this._uRL;
            }
            set
            {
                if ((value != this._uRL))
                {
                    this.OnPropertyChanging("URL", this._uRL);
                    this._uRL = value;
                    this.OnPropertyChanged("URL");
                }
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
        public override string Name
        {
            get
            {
                throw new System.InvalidOperationException("Field FileLeafRef was removed from content type ListFieldsContentType.");
            }
            set
            {
                throw new System.InvalidOperationException("Field FileLeafRef was removed from content type ListFieldsContentType.");
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
        public override string DocumentModifiedBy
        {
            get
            {
                throw new System.InvalidOperationException("Field Modified_x0020_By was removed from content type ListFieldsContentType.");
            }
            set
            {
                throw new System.InvalidOperationException("Field Modified_x0020_By was removed from content type ListFieldsContentType.");
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
        public override string DocumentCreatedBy
        {
            get
            {
                throw new System.InvalidOperationException("Field Created_x0020_By was removed from content type ListFieldsContentType.");
            }
            set
            {
                throw new System.InvalidOperationException("Field Created_x0020_By was removed from content type ListFieldsContentType.");
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "PeriodoExibicao", Storage = "_periodoExibicao", FieldType = "Choice")]
        public System.Nullable<PeriodoExibicao> PeriodoExibicao
        {
            get
            {
                return this._periodoExibicao;
            }
            set
            {
                if ((value != this._periodoExibicao))
                {
                    this.OnPropertyChanging("PeriodoExibicao", this._periodoExibicao);
                    this._periodoExibicao = value;
                    this.OnPropertyChanged("PeriodoExibicao");
                }
            }
        }

        [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Destino", Storage = "_destino", FieldType = "Choice")]
        public System.Nullable<Destino2> Destino
        {
            get
            {
                return this._destino;
            }
            set
            {
                if ((value != this._destino))
                {
                    this.OnPropertyChanging("Destino", this._destino);
                    this._destino = value;
                    this.OnPropertyChanged("Destino");
                }
            }
        }
    }

    public enum Tipo : int
    {

        None = 0,

        Invalid = 1,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Inédito")]
        Inédito = 2,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Reprise")]
        Reprise = 4,
    }

    public enum Status : int
    {

        None = 0,

        Invalid = 1,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Confirmado")]
        Confirmado = 2,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Cancelado")]
        Cancelado = 4,
    }

    public enum Categoria : int
    {
        
        None = 0,

        Invalid = 1,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Emergencial")]
        Emergencial = 2,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Atenção")]
        Atenção = 4,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Observação")]
        Observação = 8,
    }

    public enum Destino : int
    {

        None = 0,

        Invalid = 1,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Nova Janela")]
        NovaJanela = 2,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Mesma Janela")]
        MesmaJanela = 4,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Fancybox")]
        Fancybox = 8,
    }

    public enum Destino2 : int
    {

        None = 0,

        Invalid = 1,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Nova Janela")]
        NovaJanela = 2,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Mesma Janela")]
        MesmaJanela = 4,
    }

    public enum PeriodoExibicao : int
    {

        None = 0,

        Invalid = 1,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Manhã")]
        Manhã = 2,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Tarde")]
        Tarde = 4,

        [Microsoft.SharePoint.Linq.ChoiceAttribute(Value = "Noite")]
        Noite = 8,
    }

}
